# Generated by Django 3.2.2 on 2021-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buystockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
