# Generated by Django 3.2.2 on 2021-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IAA_d', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buysdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('ticker', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
