# Generated by Django 3.2.2 on 2021-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IAA_d', '0002_buysdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='activitysdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=40)),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('dtime', models.DateTimeField()),
            ],
        ),
    ]
